import { Inter } from "next/font/google";
import "./globals.css";
import StyledComponentsRegistry from './lib/registry'
import { MenuBar } from "./MenuBar";
import AuthSession from "./provider/sessionProvider";
import RecoilRootWrapper from "./recoil/RecoilRootWrapper";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "스타토",
  description: "Generated by create next app",
};

export const viewport = {
  width: 'device-width',
  initialScale: 1,
  maximumScale: 1,
  userScalable: false,
  // Also supported by less commonly used
  // interactiveWidget: 'resizes-visual',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <RecoilRootWrapper>
          <AuthSession>
            <StyledComponentsRegistry>
              {children}
              <MenuBar/>
            </StyledComponentsRegistry>
          </AuthSession>
        </RecoilRootWrapper>
      </body>
    </html>
  );
}
